version: '3.8'

services:
  apitable:
    build:
      context: .
    container_name: apitable
    restart: always
    ports:
      - '8080:80'
    environment:
      - NODE_ENV=production
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=apitable
      - DB_PASSWORD=apitablepassword
      - DB_DATABASE=apitable_db
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: apitable-postgres
    restart: always
    environment:
      POSTGRES_DB: apitable_db
      POSTGRES_USER: apitable
      POSTGRES_PASSWORD: apitablepassword
    volumes:
      - apitable-db-data:/var/lib/postgresql/data

volumes:
  apitable-db-data:
