version: '3.8'

services:
  apitable:
    image: apitable/all-in-one:latest
    container_name: apitable
    restart: always
    ports:
      - "8080:8000"
    environment:
      - NODE_ENV=production
      - DB_TYPE=postgres
      - DB_HOST=apitable-db
      - DB_PORT=5432
      - DB_USERNAME=apitable
      - DB_PASSWORD=apitablepassword
      - DB_DATABASE=apitable_db
    depends_on:
      - apitable-db

  apitable-db:
    image: postgres:15
    container_name: apitable-db
    restart: always
    environment:
      POSTGRES_DB: apitable_db
      POSTGRES_USER: apitable
      POSTGRES_PASSWORD: apitablepassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
